import Header from '../components/Header'
import PromptInput from '../components/PromptInput'
import '../styles/globals.css'

export const metadata = {
  title: 'COIN TIES4911  SMART App',
  description: 'Generated by TIES4911 Group KTM',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body>
        <Header />

        { /** Prompt input  */}
        <PromptInput />

        {children}</body>
    </html>
  )
}
